export const PLANETS = [
  /* - - Sun - - */
  {
    name: "sun",
    displayName: "Sun",
    caption: "Yellow dwarf star",
    description:
      "The Sun is the center of our solar system and source of life on Earth. The temperature in Sun's core is about 15 million °C (27 million °F).",
    year: "230 milion Earth years",
    day: null,
    radius: 695508,
    meanTemp: 5500,
    timesLarger: 109.2,
    orbitalVelocity: 0,
    orbitObject: null,
    orbitalRadius: 0,
    scaledOrbitalRadius: 0,
    rotationVelocity: 2,
    orbitalInclination: 0,
    axialTilt: 7.25,
    price: 9999,
    resources: [
      {
        name: "Solar Radiation Shielding",
        description:
          "Advanced shielding materials to protect against intense solar radiation.",
        price: 1500,
      },
      {
        name: "Thermal Insulation",
        description:
          "Heat-resistant materials to prevent spacecraft from melting in extreme temperatures.",
        price: 1000,
      },
      {
        name: "Reinforced Solar Panels",
        description:
          "Solar panels capable of withstanding extreme solar conditions.",
        price: 1200,
      },
      {
        name: "Advanced Cooling Systems",
        description:
          "Systems to dissipate excess heat generated by the spacecraft.",
        price: 800,
      },
      {
        name: "Radiation-Resistant Electronics",
        description:
          "Electronics designed to operate in high-radiation environments.",
        price: 1000,
      },
      {
        name: "Specialized Communication Systems",
        description:
          "Communication systems for transmitting data from close proximity to the Sun.",
        price: 1200,
      },
      {
        name: "Precise Navigation Systems",
        description:
          "Navigation systems ensuring the spacecraft follows the intended trajectory.",
        price: 600,
      },
      {
        name: "Advanced Power Generation",
        description:
          "Methods for generating power to operate equipment and life-support systems.",
        price: 1500,
      },
      {
        name: "Closed-Loop Life Support",
        description:
          "Life-support systems providing oxygen, food, and waste management.",
        price: 2000,
      },
      {
        name: "Robotic Probes and Sensors",
        description:
          "Probes and sensors for studying the Sun's atmosphere and conditions.",
        price: 800,
      },
    ],
  },
  /* - - Sun - - */

  /* - - Planets - - */
  {
    name: "mercury",
    price: 1499,
    displayName: "Mercury",
    caption: "Swift Planet",
    description:
      "Mercury is the fastest and smallest planet in our solar system. On the surface, the Sun would appear 3 times as large as it does from Earth.",
    year: "88 Earth days",
    day: "59 Earth days",
    moons: 0,
    distanceFromSun: 0.4,
    minTemp: -170,
    maxTemp: 449,
    radius: 2439.7,
    timesLarger: 0.38,
    orbitalVelocity: 47.9,
    orbitObject: "sun",
    orbitalRadius: 57909050,
    scaledOrbitalRadius: 24,
    rotationVelocity: 0.003,
    orbitalInclination: 7,
    axialTilt: 0.03,
    resources: [
      {
        name: "Solar Flare-Resistant Space Suits",
        description:
          "Specially designed suits with built-in shields to protect against Mercury's intense solar flares.",
        price: 500,
      },
      {
        name: "Sun-Powered Energy Crystals",
        description:
          "Crystals that harness the sun's energy on Mercury and provide a virtually endless power source.",
        price: 1000,
      },
      {
        name: "Heat-Reflecting Sunglasses",
        description:
          "High-tech shades that keep your eyes cool while exploring the scorching surface of Mercury.",
        price: 150,
      },
      {
        name: "Liquid-Cooled Jet Skis",
        description:
          "Jet skis equipped with advanced liquid-cooling technology for cruising along Mercury's hot lava rivers.",
        price: 1200,
      },
      {
        name: "Thermal Blanket Tents",
        description:
          "Insulated tents to shield you from extreme temperature fluctuations during Mercury's long days and nights.",
        price: 300,
      },
      {
        name: "Space Hammocks",
        description:
          "Hammocks designed for zero gravity, allowing you to relax and enjoy the view without floating away.",
        price: 200,
      },
      {
        name: "Solar Wind Surfboards",
        description:
          "Surfboards that harness solar wind energy for exhilarating rides above Mercury's surface.",
        price: 800,
      },
      {
        name: "Magnetic Sunscreen",
        description:
          "Sunscreen infused with magnetic particles to stay on your skin even in Mercury's low gravity.",
        price: 100,
      },
      {
        name: "Anti-Meteor Umbrellas",
        description:
          "Compact umbrellas with meteor-deflecting technology to protect you from falling space debris.",
        price: 50,
      },
      {
        name: "Lava-Proof Hiking Boots",
        description:
          "Boots designed to withstand the extreme heat and terrain of Mercury's rocky surface.",
        price: 350,
      },
    ],
  },
  {
    name: "venus",
    price: 2999,
    displayName: "Venus",
    caption: "Morning Star",
    description:
      "Venus is the hottest planet in our solar system. This is caused by its thick atmosphere which traps heat and causes greenhouse effect.",
    year: "225 Earth days",
    day: "243 Earth days",
    moons: 0,
    distanceFromSun: 0.7,
    meanTemp: 465,
    radius: 6051.8,
    timesLarger: 0.9,
    orbitalVelocity: 35.0,
    orbitObject: "sun",
    orbitalRadius: 108200000,
    scaledOrbitalRadius: 31,
    rotationVelocity: 0.003,
    orbitalInclination: 3.4,
    axialTilt: 177,
    resources: [
      {
        name: "Venusian Hovercraft",
        description:
          "High-speed hovercraft designed to glide over Venus' hot and rocky terrain.",
        price: 1200,
      },
      {
        name: "Acid-Neutralizing Space Helmets",
        description:
          "Helmets equipped with acid-neutralizing filters to breathe safely in Venus' corrosive atmosphere.",
        price: 800,
      },
      {
        name: "Cloud-Surfing Paragliders",
        description:
          "Paragliders specially designed to catch Venus' thick, sulfuric acid clouds for a thrilling ride.",
        price: 1500,
      },
      {
        name: "Laser-Cooled Ice Cream Machines",
        description:
          "Enjoy ice cream that stays frozen, even in Venus' scorching temperatures, thanks to laser cooling.",
        price: 300,
      },
      {
        name: "Solar-Powered Oxygen Generators",
        description:
          "Devices that extract oxygen from Venus' carbon dioxide atmosphere using solar energy.",
        price: 600,
      },
      {
        name: "Anti-Gravity Lounge Chairs",
        description:
          "Chairs equipped with anti-gravity technology, making relaxation effortless in Venus' high gravity.",
        price: 450,
      },
      {
        name: "Magma-Resistant Swimwear",
        description:
          "Swimwear designed to withstand the extreme heat while taking a dip in Venus' lava lakes.",
        price: 250,
      },
      {
        name: "Holographic Rainbows",
        description:
          "Create stunning holographic rainbows in Venus' dense clouds with portable projectors.",
        price: 75,
      },
      {
        name: "Super-Spicy Venusian Hot Sauce",
        description:
          "A hot sauce so spicy it can withstand Venus' scorching temperatures, adding flavor to your meals.",
        price: 30,
      },
      {
        name: "Venusian Volcano Campgrounds",
        description:
          "Campgrounds equipped with heat-resistant tents, perfect for witnessing Venus' volcanic eruptions up close.",
        price: 400,
      },
    ],
  },
  {
    name: "earth",
    price: 2025,
    displayName: "Earth",
    caption: "Blue Planet",
    description:
      "Earth is the only planet in our solar system with liquid water on its surface. The atmosphere allows us humans to breathe, while it also protects us from meteoroids.",
    year: "365.25 Earth days",
    day: "23.9 hours",
    moons: 1,
    distanceFromSun: 1,
    minTemp: -89,
    maxTemp: 58,
    radius: 6371,
    timesLarger: -1,
    orbitalVelocity: 29.8,
    orbitObject: "sun",
    orbitalRadius: 149600000,
    scaledOrbitalRadius: 37,
    rotationVelocity: 0.46,
    orbitalInclination: 0,
    axialTilt: 23.44,
    resources: [
      {
        name: "Gravity-Defying Shoes",
        description:
          "Shoes that temporarily reduce your weight, allowing you to jump higher and run faster.",
        price: 200,
      },
      {
        name: "Personal Drone Chauffeurs",
        description:
          "Autonomous drones that offer personal transportation through crowded city streets.",
        price: 800,
      },
      {
        name: "Infinite Recycling Machines",
        description:
          "Devices that instantly recycle waste materials into useful products, reducing environmental impact.",
        price: 500,
      },
      {
        name: "Instant Learning Capsules",
        description:
          "Capsules that provide knowledge and skills on any subject in seconds when ingested.",
        price: 300,
      },
      {
        name: "Time-Suspending Watches",
        description:
          "Watches that can pause time, giving you extra moments to savor life's pleasures.",
        price: 1500,
      },
      {
        name: "Eternal Energy Batteries",
        description:
          "Batteries that never run out of power and can provide energy for a lifetime.",
        price: 1000,
      },
      {
        name: "Universal Translator Earbuds",
        description:
          "Earbuds that instantly translate any language, making communication effortless.",
        price: 400,
      },
      {
        name: "Personal Weather Controllers",
        description:
          "Handheld devices that allow you to customize the weather for your ideal outdoor activities.",
        price: 700,
      },
      {
        name: "Noise-Canceling Sleep Helmets",
        description:
          "Helmets that create a peaceful, noise-free bubble for a perfect night's sleep anywhere.",
        price: 250,
      },
      {
        name: "Reality-Enhancing Glasses",
        description:
          "Glasses that add augmented reality elements to your surroundings, turning the world into a playground of possibilities.",
        price: 600,
      },
    ],
  },
  {
    name: "mars",
    price: 4999,
    displayName: "Mars",
    caption: "Red Planet",
    description:
      "Mars is our best candidate for living outside of Earth. It is the only planet we've sent rovers to. Perseverance rover's Mars samples should make it to Earth in 2033.",
    year: "1.88 Earth years",
    day: "24.6 hours",
    moons: 2,
    distanceFromSun: 1.5,
    minTemp: -125,
    maxTemp: 20,
    radius: 3389.5,
    timesLarger: 0.52,
    orbitalVelocity: 24.1,
    orbitObject: "sun",
    orbitalRadius: 227939366,
    scaledOrbitalRadius: 45,
    rotationVelocity: 0.241,
    orbitalInclination: 1.8,
    axialTilt: 25.19,
    resources: [
      {
        name: "Martian Oxygen Farms",
        description:
          "Greenhouses equipped with oxygen-producing plants to create breathable air on Mars.",
        price: 1000,
      },
      {
        name: "Red Dust-Repellent Clothing",
        description:
          "Special suits and fabrics that resist the clingy Martian dust.",
        price: 300,
      },
      {
        name: "Solar Wind Energy Generators",
        description:
          "Devices that capture energy from Mars' solar wind for sustainable power.",
        price: 800,
      },
      {
        name: "Anti-Sandstorm Goggles",
        description:
          "Goggles with advanced filters to protect your eyes during fierce Martian sandstorms.",
        price: 150,
      },
      {
        name: "Marsquake-Proof Homes",
        description:
          "Durable, flexible structures designed to withstand Mars' seismic activity.",
        price: 1200,
      },
      {
        name: "Carbonated Martian Spring Water",
        description:
          "Naturally carbonated water sourced from underground Martian springs.",
        price: 400,
      },
      {
        name: "Mars Rover Adventure Tours",
        description:
          "Guided tours on futuristic rovers for exploring the Martian landscape.",
        price: 600,
      },
      {
        name: "Mars-Grown Gourmet Cuisine",
        description:
          "Enjoy gourmet dishes made from locally grown Martian produce.",
        price: 1500,
      },
      {
        name: "Red Planet Virtual Reality",
        description:
          "Immerse yourself in virtual Martian environments from the comfort of your habitat.",
        price: 300,
      },
      {
        name: "Mars-Adapted Pets",
        description:
          "Genetically engineered pets that thrive in the Martian environment, providing companionship.",
        price: 500,
      },
    ],
  },
  {
    name: "jupiter",
    price: 8999,
    displayName: "Jupiter",
    caption: "Giant Planet",
    description:
      "Jupiter is the largest planet in our solar system. The Great Red Spot is Jupiter's super storm that is twice the size of Earth and has raged for more than 100 years.",
    year: "11.86 Earth years",
    day: "9.93 hours",
    moons: 79,
    distanceFromSun: 5.1,
    meanTemp: -110,
    radius: 69911,
    timesLarger: 11,
    orbitalVelocity: 24.1,
    orbitObject: "sun",
    orbitalRadius: 778412027,
    scaledOrbitalRadius: 72,
    rotationVelocity: 12.6,
    orbitalInclination: 1.3,
    axialTilt: 3.13,
    resources: [
      {
        name: "Gas Harvesting Drones",
        description:
          "Drones designed to extract and refine valuable gases from Jupiter's atmosphere.",
        price: 1200,
      },
      {
        name: "Jovian Energy Orbs",
        description:
          "Orbs that harness Jupiter's immense gravitational energy for long-lasting power sources.",
        price: 1000,
      },
      {
        name: "Storm-Chasing Spaceships",
        description:
          "Specially designed spacecraft for thrilling journeys through Jupiter's iconic storms.",
        price: 1500,
      },
      {
        name: "Jupiter's Candy Clouds",
        description:
          "Edible clouds of candy that drift through the jovian skies, perfect for snacking.",
        price: 300,
      },
      {
        name: "Great Red Spot Spa Retreats",
        description:
          "Relax in luxurious floating spas within the Great Red Spot, Jupiter's famous storm.",
        price: 2000,
      },
      {
        name: "Giant Magnet Fishing",
        description:
          "Engage in magnetic fishing to collect exotic metallic treasures from Jupiter's magnetic field.",
        price: 800,
      },
      {
        name: "Anti-Gravity Bungee Jumping",
        description:
          "Experience the thrill of bungee jumping in Jupiter's low gravity with added anti-gravity technology.",
        price: 1200,
      },
      {
        name: "Jovian Symphony Composer",
        description:
          "Create stunning symphonies using the unique sounds emitted by Jupiter's magnetic field.",
        price: 400,
      },
      {
        name: "Space Whale Safaris",
        description:
          "Observe and interact with mythical space whales that inhabit Jupiter's atmosphere.",
        price: 1500,
      },
      {
        name: "Jovian Trampoline Parks",
        description:
          "Bound effortlessly on trampolines set within massive inflatable domes, thanks to Jupiter's low gravity.",
        price: 1000,
      },
    ],
  },
  {
    name: "saturn",
    price: 7499,
    displayName: "Saturn",
    caption: "Ringed Planet",
    description:
      "Saturn isn't the only ringed planet in our solar system, but none are as beautiful as Saturn's. Saturn has a total of 7 rings.",
    year: "29.45 Earth years",
    day: "10.7 hours",
    moons: 82,
    distanceFromSun: 9.5,
    meanTemp: -140,
    radius: 58232,
    timesLarger: 9.1,
    orbitalVelocity: 9.7,
    orbitObject: "sun",
    orbitalRadius: 1433530000,
    scaledOrbitalRadius: 108,
    rotationVelocity: 9.87,
    orbitalInclination: 2.5,
    axialTilt: 26.73,
    resources: [
      {
        name: "Ring-Mining Drones",
        description:
          "Autonomous drones designed to mine Saturn's stunning ring system for precious minerals.",
        price: 1200,
      },
      {
        name: "Saturnian Crystal Gardens",
        description:
          "Gardens of vibrant, luminescent crystals cultivated in the caves of Saturn's moons.",
        price: 1000,
      },
      {
        name: "Ring-Resort Luxury Hotels",
        description:
          "Opulent hotels built within Saturn's rings, offering unparalleled celestial views.",
        price: 1500,
      },
      {
        name: "Anti-Gravity Roller Coasters",
        description:
          "Roller coasters that defy gravity while weaving through Saturn's ring particles.",
        price: 800,
      },
      {
        name: "Saturnian Jewelcrafting Workshops",
        description:
          "Learn to craft exquisite jewelry using Saturn's dazzling ring materials.",
        price: 1200,
      },
      {
        name: "Floating Gardens of Titan",
        description:
          "Explore lush floating gardens on Saturn's moon Titan, home to exotic flora.",
        price: 400,
      },
      {
        name: "Cassini Memorial Tours",
        description:
          "Guided tours honoring the Cassini spacecraft's historic mission to Saturn.",
        price: 600,
      },
      {
        name: "Saturnian Fashion Boutiques",
        description:
          "Discover cutting-edge fashion inspired by Saturn's colors and patterns.",
        price: 1000,
      },
      {
        name: "Rocket-Powered Ice Cream Scoops",
        description:
          "Scoops that launch scoops of ice cream into the air, creating edible fireworks.",
        price: 300,
      },
      {
        name: "Ringside Yoga Retreats",
        description:
          "Yoga retreats suspended within Saturn's rings, combining serenity with breathtaking views.",
        price: 800,
      },
    ],
  },
  {
    name: "uranus",
    price: 6499,
    displayName: "Uranus",
    caption: "Ice Giant",
    description:
      "Uranus is an icy gas giant. It is the only planet in our solar system that rotates on its side. Just like Venus, Uranus also rotates east to west.",
    year: "84 Earth years",
    day: "17 hours",
    moons: 27,
    distanceFromSun: 19.8,
    meanTemp: -195,
    radius: 25362,
    timesLarger: 4,
    orbitalVelocity: 6.8,
    orbitObject: "sun",
    orbitalRadius: 2870972000,
    scaledOrbitalRadius: 145,
    rotationVelocity: 2.59,
    orbitalInclination: 0.8,
    axialTilt: 82.23,
    resources: [
      {
        name: "Ring-Mining Drones",
        description:
          "Autonomous drones designed to mine Saturn's stunning ring system for precious minerals.",
        price: 1200,
      },
      {
        name: "Saturnian Crystal Gardens",
        description:
          "Gardens of vibrant, luminescent crystals cultivated in the caves of Saturn's moons.",
        price: 1000,
      },
      {
        name: "Ring-Resort Luxury Hotels",
        description:
          "Opulent hotels built within Saturn's rings, offering unparalleled celestial views.",
        price: 1500,
      },
      {
        name: "Anti-Gravity Roller Coasters",
        description:
          "Roller coasters that defy gravity while weaving through Saturn's ring particles.",
        price: 800,
      },
      {
        name: "Saturnian Jewelcrafting Workshops",
        description:
          "Learn to craft exquisite jewelry using Saturn's dazzling ring materials.",
        price: 1200,
      },
      {
        name: "Floating Gardens of Titan",
        description:
          "Explore lush floating gardens on Saturn's moon Titan, home to exotic flora.",
        price: 400,
      },
      {
        name: "Cassini Memorial Tours",
        description:
          "Guided tours honoring the Cassini spacecraft's historic mission to Saturn.",
        price: 600,
      },
      {
        name: "Saturnian Fashion Boutiques",
        description:
          "Discover cutting-edge fashion inspired by Saturn's colors and patterns.",
        price: 1000,
      },
      {
        name: "Rocket-Powered Ice Cream Scoops",
        description:
          "Scoops that launch scoops of ice cream into the air, creating edible fireworks.",
        price: 300,
      },
      {
        name: "Ringside Yoga Retreats",
        description:
          "Yoga retreats suspended within Saturn's rings, combining serenity with breathtaking views.",
        price: 800,
      },
    ],
  },
  {
    name: "neptune",
    price: 7999,
    displayName: "Neptune",
    caption: "Big Blue Planet",
    description:
      "Neptune is the only planet in our solar system not visible to the naked eye. NASA's Voyager 2 flew by Neptune in 1989 making it the only spacecraft to visit it up close.",
    year: "164 Earth years",
    day: "16 hours",
    moons: 14,
    distanceFromSun: 30.1,
    meanTemp: -200,
    radius: 24622,
    timesLarger: 3.9,
    orbitalVelocity: 5.4,
    orbitObject: "sun",
    orbitalRadius: 4514953000,
    scaledOrbitalRadius: 180,
    rotationVelocity: 2.6,
    orbitalInclination: 1.8,
    axialTilt: 28.32,
    resources: [
      {
        name: "Neptunian Submersible Vehicles",
        description:
          "Submersible vehicles designed for exploring Neptune's mysterious and icy oceans.",
        price: 1500,
      },
      {
        name: "Neptune's Aurora Cruise Tours",
        description:
          "Cruise tours that offer front-row seats to the spectacular auroras of Neptune's atmosphere.",
        price: 800,
      },
      {
        name: "Hydrogen-Powered Floating Cities",
        description:
          "Cities that float on Neptune's hydrogen-rich atmosphere, providing breathtaking views.",
        price: 1200,
      },
      {
        name: "Neptunian Jellyfish Farms",
        description:
          "Farms cultivating bioluminescent jellyfish as a source of food and entertainment on Neptune.",
        price: 600,
      },
      {
        name: "Neptune's Symphony Orchestra",
        description:
          "Be part of Neptune's orchestra, creating ethereal music inspired by the planet's unique sounds.",
        price: 1000,
      },
      {
        name: "Gaseous Skydiving Adventures",
        description:
          "Experience thrilling skydiving adventures in Neptune's dense and gaseous atmosphere.",
        price: 800,
      },
      {
        name: "Neptunian Space Kite Flying",
        description:
          "Fly space kites in Neptune's windswept skies for a serene and colorful experience.",
        price: 400,
      },
      {
        name: "Deep-Sea Fishing in Neptune's Oceans",
        description:
          "Join deep-sea fishing excursions to catch exotic creatures in Neptune's icy seas.",
        price: 1000,
      },
      {
        name: "Neptune's Frozen Delicacies",
        description:
          "Savor exquisite frozen desserts created from Neptune's icy treasures.",
        price: 300,
      },
      {
        name: "Magnetic Light Shows",
        description:
          "Enjoy dazzling light shows created by manipulating Neptune's magnetic field.",
        price: 700,
      },
    ],
  },
  /* - - Sun - - */

  /* - - Moons - - */
  {
    name: "moon",
    price: 999,
    displayName: "Earth's Moon",
    caption: "The brightest object in the night sky",
    description:
      "Earth's Moon is the fifth largest moon in our solar system. The Moon has so far had 24 human and more than 105 robotic visitors.",
    year: "27 days",
    radius: 1737.5,
    timesLarger: 0.27,
    distance: 385000,
    minTemp: -173,
    maxTemp: 127,
    orbitalVelocity: 1.022,
    orbitObject: "earth",
    orbitalRadius: 385000,
    scaledOrbitalRadius: 3,
    rotationVelocity: 0.005,
    orbitalInclination: 5.1,
    resources: [
      {
        name: "Lunar Habitat Modules",
        description:
          "Modular habitats for astronauts to live and work on the Moon's surface.",
        price: 2000,
      },
      {
        name: "Lunar Rovers",
        description:
          "Robust rovers for lunar surface exploration and transportation.",
        price: 1500,
      },
      {
        name: "Solar Power Arrays",
        description:
          "Efficient solar panels to harness sunlight for power on the Moon.",
        price: 800,
      },
      {
        name: "Regolith Processing Equipment",
        description:
          "Machines for processing lunar regolith into usable materials.",
        price: 1200,
      },
      {
        name: "Lunar Agriculture Kits",
        description:
          "Kits for growing crops in lunar greenhouses to sustain astronauts.",
        price: 1000,
      },
      {
        name: "Lunar EVA Suits",
        description:
          "Space suits designed for extravehicular activities on the Moon's surface.",
        price: 2500,
      },
      {
        name: "Lunar Communication Network",
        description:
          "Communication infrastructure to maintain contact with Earth and other lunar bases.",
        price: 1000,
      },
      {
        name: "Lunar Mining Drills",
        description:
          "Drilling equipment for extracting valuable minerals from the Moon.",
        price: 1800,
      },
      {
        name: "Lunar Research Laboratories",
        description:
          "Laboratories for conducting scientific experiments and research on the Moon.",
        price: 1500,
      },
      {
        name: "Lunar Waste Recycling Systems",
        description:
          "Systems for recycling waste and conserving resources in the lunar environment.",
        price: 800,
      },
    ],
  },
  {
    name: "io",
    price: 5499,
    displayName: "Io",
    caption: "Most volcanic activity",
    description:
      "Io is so volcanically active that it has lakes made of lava. Some of its volcanoes are so powerful, that with a telescope they can be seen from Earth.",
    year: "42 hours",
    radius: 1821.6,
    timesLarger: 0.285,
    distance: 262000,
    meanTemp: -143,
    orbitalVelocity: 17.334,
    orbitObject: "jupiter",
    orbitalRadius: 262000,
    scaledOrbitalRadius: 10,
    rotationVelocity: 0.07,
    orbitalInclination: 0.05,
    resources: [
      {
        name: "Io Lava Exploration Drones",
        description:
          "Robotic drones designed to explore and study Io's lava lakes and volcanic activity.",
        price: 1800,
      },
      {
        name: "Volcanic Eruption Monitoring Stations",
        description:
          "Stations equipped with sensors to monitor and study the powerful volcanic eruptions on Io.",
        price: 1500,
      },
      {
        name: "Io Lava-Resistant Research Shuttles",
        description:
          "Specialized shuttles for transporting scientists and equipment to and from Io's surface.",
        price: 2200,
      },
      {
        name: "Io Thermal Suits",
        description:
          "Highly heat-resistant suits for scientists conducting field research on Io.",
        price: 1200,
      },
      {
        name: "Io Lava Sample Collection Kits",
        description:
          "Kits for collecting and analyzing samples of Io's unique lava composition.",
        price: 1000,
      },
      {
        name: "Io Geothermal Energy Stations",
        description:
          "Geothermal energy stations harnessing heat from Io's volcanic activity for power generation.",
        price: 2500,
      },
      {
        name: "Io Communication Relay Network",
        description:
          "A network of relay stations to ensure continuous communication with Io's remote research bases.",
        price: 800,
      },
      {
        name: "Io Lava Surfing Equipment",
        description:
          "Specialized gear for adventurous lava surfing experiences on Io's surface.",
        price: 1200,
      },
      {
        name: "Io Volcano Photography Drones",
        description:
          "Drones equipped with high-resolution cameras for capturing stunning images of Io's volcanoes.",
        price: 800,
      },
      {
        name: "Io Volcanic Rock Art Studios",
        description:
          "Art studios where volcanic rocks from Io are used to create unique sculptures and artwork.",
        price: 1000,
      },
    ],
  },
  {
    name: "europa",
    price: 6999,
    displayName: "Europa",
    caption: "Life promising moon",
    description:
      "Europa's subsurface ocean of salty water contains twice as much water as Earth's oceans. It is possible, that beneath its frozen surface exists some form of life.",
    year: "85 hours",
    radius: 1560.8,
    timesLarger: 0.24,
    distance: 670900,
    minTemp: -220,
    maxTemp: -160,
    orbitalVelocity: 13.743,
    orbitObject: "jupiter",
    orbitalRadius: 670900,
    scaledOrbitalRadius: 13,
    rotationVelocity: 0.03,
    orbitalInclination: 0.47,
    resources: [
      {
        name: "Europa Subsurface Exploration Robots",
        description:
          "Robotic explorers designed to investigate Europa's subsurface ocean for signs of life.",
        price: 2200,
      },
      {
        name: "Subsurface Ice Drilling Equipment",
        description:
          "Advanced drilling tools for extracting samples from Europa's frozen surface and accessing the subsurface ocean.",
        price: 1800,
      },
      {
        name: "Europa Life Detection Sensors",
        description:
          "State-of-the-art sensors capable of detecting microbial life or organic compounds in Europa's waters.",
        price: 1500,
      },
      {
        name: "Europa Ice Submersibles",
        description:
          "Submersible vehicles equipped for exploring Europa's subsurface ocean depths.",
        price: 2500,
      },
      {
        name: "Europa Subsurface Research Laboratories",
        description:
          "Research labs deployed on Europa's surface to analyze samples and conduct experiments.",
        price: 2000,
      },
      {
        name: "Europa Ice Core Sample Preservation Kits",
        description:
          "Kits for collecting and preserving ice core samples from Europa's frozen surface.",
        price: 1000,
      },
      {
        name: "Europa Communication Relay Satellites",
        description:
          "Satellites in orbit around Europa to relay data and communications with Earth.",
        price: 1200,
      },
      {
        name: "Europa Ice Terrain Vehicles",
        description:
          "All-terrain vehicles designed to traverse Europa's icy and uneven surface.",
        price: 1800,
      },
      {
        name: "Europa Biocontainment Facilities",
        description:
          "Facilities for safely handling and studying potential extraterrestrial life samples from Europa.",
        price: 2000,
      },
      {
        name: "Europa Habitat Domes",
        description:
          "Dome-shaped habitats for scientists to live and work on Europa's surface.",
        price: 2200,
      },
    ],
  },
  {
    name: "ganymede",
    price: 7499,
    displayName: "Ganymede",
    caption: "Largest moon in the Solar System",
    description:
      "Ganymede is a moon bigger than Mercury. Ganymede has underground oceans and a faint oxygen atmosphere. It is also only moon to have its own magnetic field.",
    year: "172 hours",
    radius: 2634.1,
    timesLarger: 0.416,
    distance: 1070400,
    minTemp: -180,
    maxTemp: -113,
    orbitalVelocity: 10.88,
    orbitObject: "jupiter",
    orbitalRadius: 1070400,
    scaledOrbitalRadius: 15,
    rotationVelocity: 0.026,
    orbitalInclination: 0.2,
    resources: [
      {
        name: "Ganymede Surface Rovers",
        description:
          "Rovers designed for surface exploration on Ganymede, the largest moon in the Solar System.",
        price: 2200,
      },
      {
        name: "Subsurface Ocean Probing Devices",
        description:
          "Devices equipped to probe Ganymede's subsurface ocean and gather valuable data.",
        price: 1800,
      },
      {
        name: "Ganymede Ice Core Drills",
        description:
          "Advanced drilling equipment for extracting ice core samples from Ganymede's icy surface.",
        price: 1500,
      },
      {
        name: "Ganymede Habitat Modules",
        description:
          "Modular habitats for astronauts to establish research bases on Ganymede.",
        price: 2500,
      },
      {
        name: "Ganymede Geological Survey Drones",
        description:
          "Drones for conducting geological surveys and mapping on Ganymede's surface.",
        price: 2000,
      },
      {
        name: "Ganymede Ice Mining Equipment",
        description:
          "Equipment for mining valuable resources from Ganymede's icy crust.",
        price: 1200,
      },
      {
        name: "Ganymede Communication Relay Satellites",
        description:
          "Satellites in orbit around Ganymede to maintain communication with Earth and other bases.",
        price: 1000,
      },
      {
        name: "Ganymede Research Laboratories",
        description:
          "Laboratories for conducting scientific experiments and research on Ganymede.",
        price: 1800,
      },
      {
        name: "Ganymede EVA Suits",
        description:
          "Space suits designed for extravehicular activities on Ganymede's surface.",
        price: 2200,
      },
      {
        name: "Ganymede Solar Power Arrays",
        description:
          "Efficient solar panels for harnessing sunlight on Ganymede's surface for power generation.",
        price: 1200,
      },
    ],
  },
  {
    name: "callisto",
    price: 7299,
    displayName: "Callisto",
    caption: "The long dead moon",
    description:
      "Callisto is the most heavily cratered object in our solar system. It has almost none geologic activity on its surface, but may contain oceans beneath the surface.",
    year: "17 days",
    radius: 2410.3,
    timesLarger: 0.384,
    distance: 1883000,
    minTemp: -193,
    maxTemp: -108,
    orbitalVelocity: 8.204,
    orbitObject: "jupiter",
    orbitalRadius: 1883000,
    scaledOrbitalRadius: 17.5,
    rotationVelocity: 0.01,
    orbitalInclination: 0.28,
    resources: [
      {
        name: "Callisto Surface Exploration Rovers",
        description:
          "Rovers designed for surface exploration on Callisto, the long-dead moon of Jupiter.",
        price: 2200,
      },
      {
        name: "Callisto Ice Core Drills",
        description:
          "Advanced drilling equipment for extracting ice core samples from Callisto's icy surface.",
        price: 1800,
      },
      {
        name: "Callisto Habitat Modules",
        description:
          "Modular habitats for astronauts to establish research bases on Callisto's surface.",
        price: 2500,
      },
      {
        name: "Callisto Geological Survey Drones",
        description:
          "Drones for conducting geological surveys and mapping on Callisto's surface.",
        price: 2000,
      },
      {
        name: "Callisto Ice Mining Equipment",
        description:
          "Equipment for mining valuable resources from Callisto's icy crust.",
        price: 1200,
      },
      {
        name: "Callisto Communication Relay Satellites",
        description:
          "Satellites in orbit around Callisto to maintain communication with Earth and other bases.",
        price: 1000,
      },
      {
        name: "Callisto Research Laboratories",
        description:
          "Laboratories for conducting scientific experiments and research on Callisto.",
        price: 1800,
      },
      {
        name: "Callisto EVA Suits",
        description:
          "Space suits designed for extravehicular activities on Callisto's surface.",
        price: 2200,
      },
      {
        name: "Callisto Solar Power Arrays",
        description:
          "Efficient solar panels for harnessing sunlight on Callisto's surface for power generation.",
        price: 1200,
      },
      {
        name: "Callisto Ice Sample Preservation Kits",
        description:
          "Kits for collecting and preserving ice core samples from Callisto's frozen surface.",
        price: 1000,
      },
    ],
  },
  {
    name: "titan",
    price: 6999,
    displayName: "Titan",
    caption: "Moon with liquids on its surface",
    description:
      "Titan is the only moon in our solar system that has clouds and a dense atmosphere. There are also lakes and oceans on the surface, however they are made of methane and ethane.",
    year: "16 days",
    radius: 2574.7,
    timesLarger: 0.4,
    distance: 1221865,
    meanTemp: -179,
    orbitalVelocity: 5.57,
    orbitObject: "saturn",
    orbitalRadius: 1221865,
    scaledOrbitalRadius: 16,
    rotationVelocity: 0.011,
    orbitalInclination: 0.33,
    resources: [
      {
        name: "Titan Surface Exploration Rovers",
        description:
          "Rovers designed for surface exploration on Titan, the moon with liquids on its surface.",
        price: 2200,
      },
      {
        name: "Subsurface Ocean Exploration Submersibles",
        description:
          "Submersible vehicles designed to explore Titan's subsurface liquid oceans.",
        price: 2500,
      },
      {
        name: "Titan Habitat Modules",
        description:
          "Modular habitats for astronauts to live and work on Titan's surface.",
        price: 2500,
      },
      {
        name: "Titan Methane Research Laboratories",
        description:
          "Laboratories for studying the unique methane-based ecosystem of Titan.",
        price: 2000,
      },
      {
        name: "Titan Atmospheric Probes",
        description:
          "Probes equipped to study Titan's thick atmosphere and weather patterns.",
        price: 1800,
      },
      {
        name: "Titan Methane Extraction Equipment",
        description:
          "Equipment for extracting and processing methane as a resource on Titan.",
        price: 1500,
      },
      {
        name: "Titan Communication Relay Satellites",
        description:
          "Satellites in orbit around Titan to maintain communication with Earth and other bases.",
        price: 1000,
      },
      {
        name: "Titan Methane-Powered Generators",
        description:
          "Generators that utilize methane as a fuel source for power generation on Titan.",
        price: 1200,
      },
      {
        name: "Titan Geological Survey Drones",
        description:
          "Drones for conducting geological surveys and mapping on Titan's surface.",
        price: 2000,
      },
      {
        name: "Titan EVA Suits",
        description:
          "Space suits designed for extravehicular activities on Titan's surface and in its unique environment.",
        price: 2500,
      },
    ],
  },
  {
    name: "triton",
    price: 5999,
    displayName: "Triton",
    caption: "The coldest object in Solar system",
    description:
      "Triton is the coldest moon in our solar system. It is also the largest moon that orbits in the opposite direction of its planet's rotation.",
    year: "141 hours",
    radius: 1353.4,
    timesLarger: 0.21,
    distance: 354759,
    meanTemp: -235,
    orbitalVelocity: 4.39,
    orbitObject: "neptune",
    orbitalRadius: 354759,
    scaledOrbitalRadius: 7,
    rotationVelocity: 0.017,
    orbitalInclination: 156.885,
    resources: [
      {
        name: "Triton Surface Exploration Drones",
        description:
          "Robotic drones designed to explore Triton's frozen surface and conduct scientific research.",
        price: 2000,
      },
      {
        name: "Subsurface Ocean Exploration Submersibles",
        description:
          "Submersible vehicles equipped for exploring Triton's subsurface ocean beneath its icy crust.",
        price: 2500,
      },
      {
        name: "Triton Habitat Modules",
        description:
          "Modular habitats for astronauts to live and work on Triton's icy surface.",
        price: 2200,
      },
      {
        name: "Triton Cryogenic Laboratories",
        description:
          "Laboratories equipped to study extreme cryogenic conditions and potential subsurface oceans on Triton.",
        price: 1800,
      },
      {
        name: "Triton Geological Survey Rovers",
        description:
          "Rovers designed for conducting geological surveys and mapping on Triton's surface.",
        price: 1500,
      },
      {
        name: "Triton Ice Core Drills",
        description:
          "Advanced ice core drilling equipment for extracting samples from Triton's frozen surface.",
        price: 2000,
      },
      {
        name: "Triton Communication Relay Satellites",
        description:
          "Satellites in orbit around Triton to maintain communication with Earth and other bases.",
        price: 1000,
      },
      {
        name: "Triton Cryogenic Suits",
        description:
          "Suits specially designed for astronauts to withstand Triton's extreme cold and conduct research.",
        price: 2500,
      },
      {
        name: "Triton Cryovolcano Monitoring Stations",
        description:
          "Stations for monitoring Triton's unique cryovolcanic activity and geological phenomena.",
        price: 1500,
      },
      {
        name: "Triton Cryogenic Energy Generators",
        description:
          "Energy generators designed to operate in Triton's extreme cryogenic environment.",
        price: 2200,
      },
    ],
  },
  /* - - Moons - - */
];
